apiVersion: v1
kind: Pod
metadata:
  name: stress1
  namespace: pod-namespace
spec:
  restartPolicy: OnFailure
  schedulerName: my-scheduler
  containers:
  - name: stres1
    image: polinux/stress-ng
    resources:
      requests:
        cpu: "250m"
        memory: "250Mi"
        ephemeral-storage: "3Gi"
      limits:
        cpu: "500m"
        memory: "500Mi"
        ephemeral-storage: "4Gi"
    command: ["stress-ng"]
    args: ["--cpu","1","--cpu-load","30","--vm","1","--vm-bytes","300M","--hdd","1","--hdd-bytes","3G","--timeout","60s"]
